#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "Core/AI/TacticalLab/HellRunTacticalLabTypes.h"
#include "TacticalLabScenarioAsset.generated.h"

class UTexture2D;
class UEnvQuery;

UENUM(BlueprintType)
enum class ETacticalLabEQSRunMode : uint8
{
    SingleResult,
    RandomBestFivePercent,
    RandomBestTwentyFivePercent,
    AllMatching,
};

/** Portable authored scenario opened by the native Tactical AI Lab editor. */
UCLASS(BlueprintType)
class HELLRUNTACTICALLAB_API UTacticalLabScenarioAsset : public UDataAsset
{
    GENERATED_BODY()

public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Scenario")
    FHellRunTacticalLabScenario Scenario;

    /** Optional orthographic map bake displayed below the tactical overlays. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Map")
    TSoftObjectPtr<UTexture2D> TacticalMapTexture;

    /** Static session preview generated by Bake Map without asset/DDC processing. */
    UPROPERTY(Transient)
    TObjectPtr<UTexture2D> GeneratedMapPreview;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Map")
    FSoftObjectPath SourceMap;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Display")
    bool bShowGrid = true;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Display")
    bool bShowGeometry = true;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Display")
    bool bShowCandidates = true;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Display")
    bool bShowTraversal = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Display")
    bool bShowLabels = true;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Display|Layers")
    bool bShowEntities = true;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Display|Layers")
    bool bShowRoutes = true;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Display|Layers")
    bool bShowEQS = true;

    /** Locked layers render normally but cannot win canvas hit testing. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Display|Layer Locks")
    bool bLockEntities = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Display|Layer Locks")
    bool bLockGeometry = true;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Display|Layer Locks")
    bool bLockRoutes = true;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Display|Layer Locks")
    bool bLockHazards = true;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Display|Vision")
    bool bShowVisionCones = true;

    /** Draw the unoccluded perception configuration. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Display|Vision")
    bool bShowConfiguredFOV = true;

    /** Draw the result after LOS blockers clip the configured FOV. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Display|Vision")
    bool bShowResolvedVisibility = true;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Display|Vision",
        meta=(ClampMin="100.0", ClampMax="20000.0", Units="cm"))
    float VisionConeRange = 2500.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Display|Vision",
        meta=(ClampMin="5.0", ClampMax="89.0", Units="Degrees"))
    float VisionConeHalfAngleDegrees = 52.5f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Live EQS")
    bool bEnableLiveEQS = true;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Live EQS")
    TSoftObjectPtr<UEnvQuery> LiveEQSQuery;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Live EQS")
    ETacticalLabEQSRunMode LiveEQSRunMode = ETacticalLabEQSRunMode::AllMatching;

    /** Passed to FEnvQueryRequest as named float parameters. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Live EQS")
    TMap<FName,float> LiveEQSNamedParameters;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Live EQS")
    float LiveEQSQueryHeightOffset = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Live EQS",
        meta=(ClampMin="0.05", ClampMax="2.0"))
    float LiveEQSDebounceSeconds = 0.15f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Live EQS",
        meta=(ClampMin="1", ClampMax="5000"))
    int32 MaximumDisplayedEQSItems = 500;
};
